---
- name: ensure cryptsetup package installed
  package:
    name: cryptsetup
    state: present

- name: load crypt key file
  template:
    src: templates/keyfile.j2
    dest: "/root/{{ crypt_name }}.txt"
    owner: root
    group: root
    mode: 0600

- name: Luks Format Device
  command: "cryptsetup --batch-mode --key-file /root/{{crypt_name}}.txt luksFormat {{ crypt_backing_device }}"
  when: crypt_init is defined

- name: Luks Open
  command: "cryptsetup luksOpen --key-file /root/{{crypt_name}}.txt {{ crypt_backing_device }} {{ crypt_name }}"
  when: crypt_init is defined

- name: Make file system
  command: "mkfs.ext4 /dev/mapper/{{ crypt_name }}"
  when: crypt_init is defined

- name: setup the crypttab
  crypttab:
    state: present
    name: "{{ crypt_name }}"
    backing_device: "{{ crypt_backing_device }}"
    password: "/root/{{ crypt_name }}.txt"
    opts: luks
  no_log: true

- name: unlock encrypted directory
  command: /usr/sbin/cryptdisks_start {{ crypt_name|quote }}

- name: setup mountpoint
  mount:
    state: mounted
    path: "{{ crypt_mount_point }}"
    fstype: ext4
    src: "/dev/mapper/{{ crypt_name }}"
