---
cloud_snitch_conf_dir: /etc/cloud_snitch
cloud_snitch_data_dir: "{{ cloud_snitch_conf_dir }}/data"
cloud_snitch_conf_file: "{{ cloud_snitch_conf_dir }}/cloud_snitch.yml"
cloud_snitch_log_level: 'INFO'
cloud_snitch_log_format: '%(name)s %(levelname)s - %(message)s'

cloud_snitch_environment_account_number: unknown
cloud_snitch_environment_name: unknown

cloud_snitch_neo4j_enabled: True
cloud_snitch_neo4j_password: password
cloud_snitch_neo4j_username: neo4j
cloud_snitch_neo4j_uri: bolt://localhost
cloud_snitch_neo4j_log_level: 'WARNING'
cloud_snitch_neo4j_max_retries: 10

cloud_snitch_sync_venv: '/opt/venvs/cloudsnitch'

cloud_snitch_repo: https://github.com/rcbops/FleetDeploymentReporting.git
cloud_snitch_version: master

cloud_snitch_sync_pip_list:
  neo4j-driver: '1.5.3'
  PyYAML: '3.12.'
  pytz: '2016.6.1'

cloud_snitch_git_repo_list: []
cloud_snitch_file_list: []
