---
- name: Clone cloud_snitch git repo
  become: yes
  git:
    repo:  "{{ cloud_snitch_repo }}"
    dest:  "{{ cloud_snitch_repo_dir }}"

- name: Install GitPython into ansible runtime venv
  become: yes
  pip:
    name: "{{ git_python }}"
    version: "{{ git_python_version }}"
    extra_args: --isolated

- name: Create Directories
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ cloud_snitch_conf_dir }}"
    - "{{ cloud_snitch_data_dir }}"
  tags:
    - config

- name: Template cloud_snitch.yml config
  become: yes
  template:
    src: cloud_snitch.yml.j2
    dest: "{{ cloud_snitch_conf_file }}"
  tags:
    - config

- name: Template cloud_snitch.rc
  become: yes
  template:
    src: cloud_snitch.rc.j2
    dest: "{{ cloud_snitch_rc_file }}"
  tags:
    - config

- name: Cloud Snitch Sync - Virtualenv
  command: "virtualenv {{ cloud_snitch_sync_venv }} -p python3.5"
  args:
    creates: "{{ cloud_snitch_sync_venv }}/bin/activate"
  when: cloud_snitch_sync_enabled

- name: Cloud Snitch Sync - Pip Packages
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    virtualenv: "{{ cloud_snitch_sync_venv }}"
    extra_args: --isolated
  with_dict: "{{ cloud_snitch_sync_pip_list }}"
  when: cloud_snitch_sync_enabled

- name: Cloud Snitch Sync - Isntall Sync
  pip:
    name: "git+{{ cloud_snitch_repo }}@{{ cloud_snitch_version }}"
    virtualenv: "{{ cloud_snitch_sync_venv }}"
  when: cloud_snitch_sync_enabled
